public enum ArnoldCLexemes {

  FALSE("@I LIED"),
  TRUE("@NO PROBLEMO"),
  IF("BECAUSE I'M GOING TO SAY PLEASE"),
  ELSE("BULLSHIT"),
  ENDIF("YOU HAVE NO RESPECT FOR LOGIC"),
  WHILE("STICK AROUND"),
  ENDWHILE("CHILL"),
  ADD("GET UP"),
  SUBTRACT("GET DOWN"),
  MULTIPLY("YOU'RE FIRED"),
  DIVIDE("HE HAD TO SPLIT"),
  MODULO("I LET HIM GO"),
  EQUALEQUAL("YOU ARE NOT YOU YOU ARE ME"),
  GREATERTHAN("LET OFF SOME STEAM BENNET"),
  OR("CONSIDER THAT A DIVORCE"),
  AND("KNOCK KNOCK"),
  DECLAREMETHOD("LISTEN TO ME VERY CAREFULLY"),
  // NONVOIDMETHOD("GIVE THESE PEOPLE AIR"),
  // METHODARGUMENTS("I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE"),
  // RETURN("I'LL BE BACK"),
  // ENDMETHOD("HASTA LA VISTA, BABY"),
  // CALLMETHOD("DO IT NOW"),
  ASSIGNVARIABLEFROMMETHODCALL("GET YOUR ASS TO MARS"),
  DECLAREINTEGER("HEY CHRISTMAS TREE"),
  SETINITIALVALUE("YOU SET US UP"),
  BEGINMAIN("IT'S SHOWTIME"),
  ENDMAIN("YOU HAVE BEEN TERMINATED"),
  PRINT("TALK TO THE HAND"),
  READINTEGER("I WANT TO ASK YOU A BUNCH OF QUESTIONS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY"),
  ASSIGNVARIABLE("GET TO THE CHOPPER"),
  SETVALUE("HERE IS MY INVITATION"),
  ENDASSIGNVARIABLE("ENOUGH TALK");

  /*
  Data type ("value")
    in a lexer, it the token (containing its lexeme, and data type)
  INTEGER("[0-9]"),
  ADDOPERATION("GET UP"),
  SUBTRACTOPERATION("GET DOWN"),
  MULTIPLYOPERATION("YOU'RE FIRED"),
  DIVIDEOPERATION("HE HAD TO SPLIT"),
  MODULOOPERATION("I LET HIM GO"),



  */


  private String s;

  private ArnoldCLexemes(String s){
    this.s = s;
  }
//pahingi access sa arnoldctokenizer.java
  public String svalue(){
    return this.s;
  }

}
